export const ACCOUNT_MODULE = "[ACCOUNT_MODULE]";

export const accountActions = {
  FETCH_ACCOUNT_INFO : "[FETCH_ACCOUNT_INFO]",
  LOAD_MORE_USER_LISTINGS : "[LOAD_MORE_USER_LISTINGS]",
  LOAD_MORE_FAVORITE_LISTINGS : "[LOAD_MORE_FAVORITE_LISTINGS]",
  REMOVE_FROM_FAVORITE_LISTINGS : "[REMOVE_FROM_FAVORITE_LISTINGS]",
  DELETE_LISTING : "[DELETE_LISTING]"
};


export const accountMutations = {
    FETCH_ACCOUNT_INFO_START : "[FETCH_ACCOUNT_INFO_START]",
    LOAD_MORE_USER_LISTINGS_START : "[LOAD_MORE_USER_LISTINGS_START]",
    LOAD_MORE_FAVORITE_LISTINGS_START : "[LOAD_MORE_FAVORITE_LISTINGS_START]",

    PUT_ACCOUNT_INFO : "[PUT_ACCOUNT_INFO]",
    PUT_USER_INFO : "[PUT_USER_INFO]",
    PUT_USER_LISTINGS : "[PUT_USER_LISTINGS]",
    PUT_USER_FAVORITES_LISTINGS : "[PUT_USER_FAVORITES_LISTINGS]",

    FAVORITE_ACTION_START : "[FAVORITE_ACTION_START]",
    REMOVE_LISTING_FROM_FAVORITES : "[REMOVE_LISTING_FROM_FAVORITES]",

    HIDE_LOGOUT_DIALOG : "[HIDE_LOGOUT_DIALOG]",
    OPEN_LOGOUT_DIALOG : "[OPEN_LOGOUT_DIALOG]",

    UPDATE_USER_PASSWORD : "[UPDATE_USER_PASSWORD]",

    DELETE_ACTION_START : "[DELETE_ACTION_START]",
    PUT_LISTING_ID_FOR_DELETE : "[PUT_LISTING_ID_FOR_DELETE]",
    REMOVE_LISTING_FROM_LIST : "[REMOVE_LISTING_FROM_LIST]",
    HIDE_DELETE_DIALOG : "[HIDE_DELETE_DIALOG]",
};