export const MAIN_PAGE = "[MAIN_PAGE]";

export const mainPageActions = {
     FETCH_MAIN_PAGE_DETAILS : "[FETCH_MAIN_PAGE_DETAILS]",
     SET_ACTIVE_CATEGORY : "[SET_ACTIVE_CATEGORY]",
     SEARCH_LISTINGS_BY_PARAMS : "[SEARCH_LISTINGS_BY_PARAMS]",
     LOAD_MORE_LISTINGS_BY_PARAMS : "[LOAD_MORE_LISTINGS_BY_PARAMS]",
};

export const  mainPageMutations = {
     FETCH_MAIN_PAGE_START : "[FETCH_MAIN_PAGE_START]",
     PUT_MAIN_PAGE_DETAILS : "[PUT_MAIN_PAGE_DETAILS]",
     PUT_ACTIVE_CATEGORY : "[PUT_ACTIVE_CATEGORY]",
     PUT_ACTIVE_CITY : "[PUT_ACTIVE_CITY]",
     PUT_SEARCH_TERM : "[PUT_SEARCH_TERM]",
    SET_LAST_CATEGORY : "[SET_LAST_CATEGORY]",
    RESET_CITY : "[RESET_CITY]",
    RESET_CATEGORY : "[RESET_CATEGORY]",
};
