export const MAIN_LISTINGS = "[MAIN_LISTINGS]";

export const mainListingsActions = {
    FETCH_RECENT_LISTINGS : "[FETCH_RECENT_LISTINGS]",
    FETCH_MORE_LISTINGS : "[FETCH_MORE_LISTINGS]"
};

export const mainListingsMutations = {
    FETCH_RECENT_LISTINGS_START : "[FETCH_RECENT_POSTS_START]",
    PUT_RECENT_LISTINGS : "[PUT_RECENT_LISTINGS]",
    FETCH_MORE_LISTINGS_START : "[FETCH_MORE_LISTINGS_START]",
    PUT_MORE_LISTINGS : "[PUT_MORE_LISTINGS]"
};