export const SINGLE_LISTING_MODULE  = "[SINGLE_LISTING_MODULE]";

export const singleListingActions = {
    FETCH_SINGLE_LISTING : "[FETCH_SINGLE_LISTING]",
    TOGGLE_FAVORITE_LISTING : "[TOGGLE_FAVORITE_LISTING]",
};

export const singleListingMutations = {
    FETCH_SINGLE_LISTING_START : "[FETCH_SINGLE_LISTING_START]",
    PUT_SINGLE_LISTING : "[PUT_SINGLE_LISTING]",
    PUT_FAVORITE_LOADING : "[PUT_FAVORITE_LOADING]",
    UPDATE_FAVORITE_STATUS : "[UPDATE_FAVORITE_STATUS]",
    HIDE_FAVORITE_ACTION_LOADER : "[HIDE_FAVORITE_ACTION_LOADER]",
};
